### ISSUE TITLE
Add a scroll bar and multiple pages to the home screen with the list of proposals

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#114]
Remove the box, add a scroll bar to the list of proposals and also have a dropdown menu to let users choose how many rows/proposals they'd like to see per page, e.g. 10, 20, 30. At the bottom there will be links  "< previous 1,2,3,4,5,....15 next > "

**Comment by adamazad** [comment]
This is very similar to #90

**Comment by rossneilson** [comment]
Since we have all the data available having on the client at the same time currently and pagination is not simple with how we currently fetch cached data (ipfs + onchain data) the infinite scroll is a better approach generally.
A scrollbar also got added in another PR, further CSS changes could be made in future, closing for now.
