### ISSUE TITLE
Pending boost time loop

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#138]
Not sure if this is a UI issue or if the proposal needs to be 'pushed to the boosting phase'

**To Reproduce**
Submit and boost on DXvote? This is on Augusto's worker proposal

video attached

https://user-images.githubusercontent.com/47428627/132894363-750762df-d3fe-4e5a-8052-3d51696b54f9.mov

**Comment by AugustoL** [comment]
This bug can be reproduced in non wallet scheme type schemes. Where the proposals finish time is boost date + boost time period. 

In the wallet scheme the boos is done "automatically", so here you see the delay between blocks, since it advance a few seconds and gets again to 4 days, which is the boosted time period in contribution reward scheme.

If the scheme does not boost automatically we have to show the fixed time like "Finish in 4 days after boost" or smth like that instead of the counter
