### ISSUE TITLE
Timestamps and Ordering of Proposals

### ISSUE THREAD

**Issue by jpkcambridge** [DXgovernance/dxvote#209]
**Problem Description**
Cannot tell when or in what order proposals were made

**Desired Solution**
Add creation timestamp column to main proposal page and display in chronological order (might need to think about this more with different stages etc.)

It's important to understand the order proposals were made in and also very important (i.e. critical for security) to not bury proposals.

**Comment by luchux** [comment]
It's a good idea. We should rethink the layout, since the table got a bit compress with the Grid of the Filter | Table on the same row. Adding a new column will compress more the table, unless we move the Filter up again. 
@rossneilson  thoughts?

**Comment by rossneilson** [comment]
If we were to only make the timestamp be on finished proposals we could likely just remove something like the staking details since they are not very important for finished proposals.
Also in #171 this could be done better as we would have more space

**Comment by luchux** [comment]
awesome!
i can take this if no one is on it.

**Comment by rossneilson** [comment]
Go for it!

**Comment by luchux** [comment]
@rossneilson @jpkcambridge 
at the moment proposals are sorted By: 
.filter(proposal => proposal.stateInVotingMachine === p)
        .sort((a, b) =>
          a.boostTime.toNumber() > 0
            ? b.boostTime.toNumber() - a.boostTime.toNumber()
            : b.finishTime - a.finishTime
        )
        
Should we exclude this sorting and just focus on creation time of the proposal with a crated at column (clickeable to sort / revserse sort)?

Or should we filter by an action button in the menu, something like: 
<img width="1440" alt="Screen Shot 2021-10-06 at 4 23 34 PM" src="https://user-images.githubusercontent.com/1475656/136296906-509d3975-21a1-47a9-aa6c-94dae2c57872.png">
<img width="1440" alt="Screen Shot 2021-10-06 at 4 23 14 PM" src="https://user-images.githubusercontent.com/1475656/136296914-689adc58-512c-40bd-af88-1632c2a6940d.png">

**Comment by rossneilson** [comment]
So we talked about this a little last night and it seemed the concensus we came to was a somewhat complex one.

A simple creation date sorting is not what we want. The first most important is how we currently do it, sorting by status, this is how most of the time users will look for proposals as they likely want to see the ones that are boosted since they can vote on those without losing REP. 
Secondly of course we should have items in those groups sorted by time (created / time to finish depending on state).
However beyond this we also want some more overrides, for example if an unboosted proposal has gained over a set percentage or is close to passing this should be near the top as it is as important as 
Close to passing (boosted/lots of votes & live proposal) -> status -> time (newest first)

Currently there is a bug also where it seems the proposals are not sorting newest to oldest and instead the other way around. Check arbitrum to clearly see that epoch 2 proposals are at the very bottom despite being newer than epoch 1.

This may be better in another issue but some spacing element between live and finished proposals would be useful also.

**Comment by AugustoL** [comment]
Order of priority on the proposals:

1. Proposals in Queued or QuietEndingPeriod status with more than 10% of positive votes. (Ordered from time to finish, from lower to higher)
2. Proposals Boosted.  (Ordered from time to finish, from lower to higher)
3. Proposals Pre Boosted.
4. Proposals in Queued or QuietEndingPeriod status with lower than 10% of positive votes. (Ordered from time to finish, from lower to higher)
5. Proposals in Executed status. (Ordered in time passed since finish, from lower to higher)

The VotingMachine status are in the utils/enums.ts file, and they are easy to access in the proposal object.

right @rossneilson ?

**Comment by luchux** [comment]
rad! will test the actual function and fix based on this criteria.

**Comment by rossneilson** [comment]
> right @rossneilson ?

Well summarised :D

**Comment by luchux** [comment]
PR: https://github.com/DXgovernance/dxvote/pull/240
