### ISSUE TITLE
Multicall UX/UI improvements on call data

### ISSUE THREAD

**Issue by fluiddrop** [DXgovernance/dxvote#318]
It would be nice to have call data decoded, just to double check parameters in DXvote. I really like having the ability to paste encoded call data right away - instead of having to manually enter each parameters and being forced to encode on the site (like alchemy). 

But for UI/UX it might make sense to offer both options? 

And when you post encoded ABI call - it would be sweet to decode it so one can throw a quick glance at the params.

**Comment by rossneilson** [comment]
The main immediate use here is for the DAOstack multicalls which we dont want to put too much effort into additional features for due to the goal of deprecating them.

However this would also be a useful feature for relayers or any proposals where we need to allow calldata in a parameter.

The ideal solution would be, as highlighted by Dave, the ability to enter both in encoded calldata or manually per human readable decoded param. Also the proposal view should show the fully decoded, stacked calldata.

Adding this to the "Custom" proposal type interface would bloat that code even more and so I think the best implementation would be a `StackedCallDataInput` component that can be reused and implemented on `DAOstack multicall`, `Buyback` and `Relayer` proposal types, following the new UX flow. 

This could even go multiple levels down with calldata in future
