### ISSUE TITLE
Double event recording to local cache

### ISSUE THREAD

**Issue by pimato** [DXgovernance/dxvote#396]
**Description**
I just voted on [Ross Proposal](https://dxvote.dev/#/xdai/proposal/0xd8680f64a49f9b16f34e4399620e2b96be3dd4707161a4a7d8dfbbc591b210f8)
and it seems like the UI is showing two vote entries now in the positive vote list:
<img width="345" alt="Screenshot 2021-11-18 at 13 15 14" src="https://user-images.githubusercontent.com/5337809/142422172-a1b643a4-a5df-4524-90d9-caa12dbc7ccc.png">

**Steps to Reproduce**

1. Go to https://dxvote.dev/#/xdai
2. Click on any active proposal
3. Vote on a proposal
4. See double entry in the voting list. I tried to reproduce it, it did not work though.

**Expected behavior**
Entry list should only show the vote once.

**Screenshots**
<img width="345" alt="Screenshot 2021-11-18 at 13 15 14" src="https://user-images.githubusercontent.com/5337809/142422172-a1b643a4-a5df-4524-90d9-caa12dbc7ccc.png">
**Device Information**

- OS: MacOS
- Browser Brave
- Version Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (x86_64)
- Device: Macbook Air

**Comment by rossneilson** [comment]
I also saw geronimo's vote come through twice so looks like it may be when the UI is parsing individual blocks as they come through when open.

**Comment by KeenanLukeOM** [comment]
## Description

I had was unable to vote without a contract exception being thrown on both of my proposals. Inputting a very slightly lower REP percentage (0.01%) allowed me to post it immediately:

https://dxvote.eth.link/#/xdai/proposal/0x04450726f680f9ff7e6a8f175ed4fbc1652fe2b1dbd9f7802ee225d70411d00c

https://dxvote.eth.link/#/xdai/proposal/0x65f076e56e038461aeb6a8b4c54f79c7fcd43b081022f2282ca83b5130760cd9

But I did NOT experience this on another proposal that I did not create. I was able to simple click vote without issue:

https://dxvote.eth.link/#/xdai/proposal/0x9b2e7814a9b00111f9a8adb8822bc21fb9cc1a3d873b770a7a597385447cd850

## Expected Behavior

Clicking vote with my autofilled max REP allocation should throw no exception and vote with my maximum REP on the address.

## Device information
- OS: Windows 10
- Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by rossneilson** [comment]
So I am fairly confident both of these issues are related as they both seem to be caused by blocks being parsed twice.

We do this in fetchData() in BlockchainStore. Every so often we check current block and if new blocks are available we then fetch them and parse out any events which may have occurred. 
What I think is happening here is that the blocks are being parsed twice and this results in repEvents and votes being stored locally twice.

This was just a small UI bug with votes appearing twice but the issue comes with repEvents since the UI tries to vote with more REP that it has, causing an error that prevents people from voting. 

Possible solutions: 

- Prevent the block from being parsed twice
- Check for duplicate data being entered into local cache

Local cache can be found here in the browser:
<img width="745" alt="Screenshot 2021-11-18 at 18 14 33" src="https://user-images.githubusercontent.com/39137239/142473036-96a36102-766f-4e96-939f-62a997e22b03.png">
