### ISSUE TITLE
Feature to flag incorrect proposals.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#592]
Allow the address that has submitted a proposal to leave a mark and append it with a comment to notify stakers/voters if the proposal/parameters are found to be incorrect. Also, a request to sign a message with the info could popup when anyone tries to interact with such a proposal.

A solution requiring more time and effort could be updating contracts in the future to allow the address that created a proposal to fast-track it to expiry before anyone else has interacted with it.

**Comment by rossneilson** [comment]
Since having the option to cancel the proposal would require some smart contract changes we can have an interim approach here. 
Since most cases where proposals should be cancelled are mistakes being made in proposal creation we could assume that if the proposer votes against their own proposal then it is likely to be cancelled.
We could then display a warning message to other voters to ensure it doesn't accidentally get voted through.
