### ISSUE TITLE
Fixed size proposal cards

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#615]
We have a lot of movement as things load in guilds right now.
We can fix this by setting the height of placeholder loading animations to be the same as the real content

**Comment by mprasanjith** [comment]
I think this is because we have the loading state as a different component. react-loading-skeleton suggests [not to use](https://github.com/dvtng/react-loading-skeleton#dont-make-dedicated-skeleton-screens) dedicated loading components. Changing this will probably fix most of the stylistic differences here.
