### ISSUE TITLE
Pressing boost button, changes state to execution failed

### ISSUE THREAD

**Issue by dRAT3** [DXgovernance/dxvote#64]
**Describe the bug**
When pressing the boost button the proposal state changes to execution failed. I had this happen before the last update. And now it happened again after the update. It was on this proposal -> https://augustol.github.io/dxvote/#/proposal/0x40c56d6f49a48d729079d7f98926453981cd1f52910b0414da769190993af5e7 . The proposal from before the update has dissapeared.

**To Reproduce**
1. Go to a proposal that has a boost button
2. Click on "Boost"
3. Wait for confirmation of transaction

**Expected behavior**
For the proposal to become boosted. Or the proposal to show that it has been boosted before and the  button to show execute

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Brave

**Comment by AugustoL** [comment]
This happens because in difference as mainnnet we automatically execute the pre-boosted boosted state and execute proposal if possible.

The state in voting machine and scheme shown is the correct,
 State in Voting Machine Executed
State in Scheme ExecutionSucceded

But the one in the proposal is not, going to fix it, is a small bug.
